# Generated by Django 4.2.6 on 2023-10-16 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='destination',
            table='destinations',
        ),
    ]
